# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.srcs/sources_1/ip/pll_clk_gen/pll_clk_gen.xci
# IP: The module: 'pll_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.gen/sources_1/ip/pll_clk_gen/pll_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.gen/sources_1/ip/pll_clk_gen/pll_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.gen/sources_1/ip/pll_clk_gen/pll_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.srcs/sources_1/ip/pll_clk_gen/pll_clk_gen.xci
# IP: The module: 'pll_clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.gen/sources_1/ip/pll_clk_gen/pll_clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.gen/sources_1/ip/pll_clk_gen/pll_clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.gen/sources_1/ip/pll_clk_gen/pll_clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
