# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.srcs/sources_1/ip/temp_lut_rom/temp_lut_rom.xci
# IP: The module: 'temp_lut_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.gen/sources_1/ip/temp_lut_rom/temp_lut_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'temp_lut_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.srcs/sources_1/ip/temp_lut_rom/temp_lut_rom.xci
# IP: The module: 'temp_lut_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Marcus/Documents/Vivado/ee410_XADC_Project/ee410_XADC_Project.gen/sources_1/ip/temp_lut_rom/temp_lut_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'temp_lut_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
